### ISSUE TITLE
Location is not available

### ISSUE THREAD

**Issue by D0ragn** [ExtendLord/DeezLoader-Reborn#49]
I put an album to download, in the program everything is working fine, when it finish I try to open the album folder then a windows message appears: the location is not available.
The album folder is impossible to delete, also it is 0 bytes in there

**Comment by ExtendLord** [comment]
Link for the album/playlist/track?

**Comment by D0ragn** [comment]
http://www.deezer.com/album/759189

**Comment by D0ragn** [comment]
I downloaded as flac

**Comment by ExtendLord** [comment]
Trailing dot problem, did you upgraded to 3.0.2?
Because it got fixed in 3.0.2.

**Comment by D0ragn** [comment]
I'm unable to delethe the folder from the download directory even if i use system symbol

**Comment by ExtendLord** [comment]
@D0ragn It is because the folder ends with dots.
Upgrade deezloader to 3.0.2 and delete that folder using cmd

**Comment by D0ragn** [comment]
I upgrade to 3.0.2 I reboot my pc. I downloaded the same album, the program crashes and exit

**Comment by D0ragn** [comment]
I'm still unable to delete the folder even if I use CMD, the location doesn't exist and the file is empty but folder is already there

**Comment by virtualviolet** [comment]
Try using: https://www.wisecleaner.com/wise-force-deleter.html

**Comment by D0ragn** [comment]
@virtualviolet Thanks for the tool It Works

**Comment by virtualviolet** [comment]
no problem
